/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author joaquicenos
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    private Model model;
    private Controller controller;
    
    public View(Model m) {
        model = m;
        initComponents();
        asignEvents();
    }
    public Controller getController() {
        if(controller == null){
            controller = new Controller(this);
        }
        return controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDesplazamiento = new javax.swing.JPanel();
        lblRotacion = new javax.swing.JLabel();
        lblDespX = new javax.swing.JLabel();
        sldRotacion = new javax.swing.JSlider();
        sldPinza = new javax.swing.JButton();
        sldDespY = new javax.swing.JSlider();
        lblPinza = new javax.swing.JLabel();
        sldDespX = new javax.swing.JSlider();
        lblDespY = new javax.swing.JLabel();
        panelAngulos = new javax.swing.JPanel();
        lblAlfa2 = new javax.swing.JLabel();
        sldAlfa2 = new javax.swing.JSlider();
        sldAlfa3 = new javax.swing.JSlider();
        lblControlBrazos = new javax.swing.JLabel();
        lblAlfa4 = new javax.swing.JLabel();
        sldAlfa1 = new javax.swing.JSlider();
        lblAlfa1 = new javax.swing.JLabel();
        lblAlfa3 = new javax.swing.JLabel();
        sldAlfa4 = new javax.swing.JSlider();
        topView = new java.awt.Canvas();
        armView = new java.awt.Canvas();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        pnlCoordenadas = new javax.swing.JPanel();
        lblArtCPosX = new javax.swing.JLabel();
        lblArtDPosY = new javax.swing.JLabel();
        lblArtAPosY = new javax.swing.JLabel();
        lblArtCPosY = new javax.swing.JLabel();
        lblArtDPosZ = new javax.swing.JLabel();
        lblArtB = new javax.swing.JLabel();
        lblArtAPosX = new javax.swing.JLabel();
        lblArtAPosZ = new javax.swing.JLabel();
        lblArtA = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblArtBPosY = new javax.swing.JLabel();
        lblPosY = new javax.swing.JLabel();
        lblArtBPosZ = new javax.swing.JLabel();
        lblArtBPosX = new javax.swing.JLabel();
        lblArtC = new javax.swing.JLabel();
        lblArtCPosZ = new javax.swing.JLabel();
        lblPosX = new javax.swing.JLabel();
        lblArtDPosX = new javax.swing.JLabel();
        lblPosZ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 950));

        lblRotacion.setText("Rotación del Robot");

        lblDespX.setText("Desplazamiento del Robot  en X");

        sldRotacion.setMajorTickSpacing(30);
        sldRotacion.setMaximum(360);
        sldRotacion.setPaintLabels(true);
        sldRotacion.setValue(0);

        sldPinza.setText("Click");

        sldDespY.setMajorTickSpacing(100);
        sldDespY.setMaximum(800);
        sldDespY.setPaintLabels(true);
        sldDespY.setValue(400);

        lblPinza.setText("Abrir/Cerrar Pinza");

        sldDespX.setMajorTickSpacing(100);
        sldDespX.setMaximum(800);
        sldDespX.setPaintLabels(true);
        sldDespX.setValue(400);

        lblDespY.setText("Desplazamiento del Robot  en Y");

        javax.swing.GroupLayout panelDesplazamientoLayout = new javax.swing.GroupLayout(panelDesplazamiento);
        panelDesplazamiento.setLayout(panelDesplazamientoLayout);
        panelDesplazamientoLayout.setHorizontalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblDespY))
                    .addComponent(sldDespY, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblRotacion))
                    .addComponent(sldRotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblPinza)
                        .addGap(23, 23, 23)
                        .addComponent(sldPinza))
                    .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblDespX))
                    .addComponent(sldDespX, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelDesplazamientoLayout.setVerticalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDesplazamientoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblPinza))
                    .addComponent(sldPinza))
                .addGap(20, 20, 20)
                .addComponent(lblDespX)
                .addGap(20, 20, 20)
                .addComponent(sldDespX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblDespY)
                .addGap(20, 20, 20)
                .addComponent(sldDespY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblRotacion)
                .addGap(25, 25, 25)
                .addComponent(sldRotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblAlfa2.setText("alfa 2");

        sldAlfa2.setMajorTickSpacing(30);
        sldAlfa2.setMaximum(175);
        sldAlfa2.setMinimum(5);
        sldAlfa2.setPaintLabels(true);
        sldAlfa2.setValue(135);
        sldAlfa2.setName("alfa2"); // NOI18N

        sldAlfa3.setMajorTickSpacing(30);
        sldAlfa3.setMaximum(175);
        sldAlfa3.setMinimum(5);
        sldAlfa3.setPaintLabels(true);
        sldAlfa3.setValue(135);
        sldAlfa3.setName("alfa3"); // NOI18N

        lblControlBrazos.setText("Control de los Brazos");

        lblAlfa4.setText("alfa 4");

        sldAlfa1.setMajorTickSpacing(30);
        sldAlfa1.setMaximum(175);
        sldAlfa1.setMinimum(5);
        sldAlfa1.setPaintLabels(true);
        sldAlfa1.setValue(90);
        sldAlfa1.setName("alfa1"); // NOI18N

        lblAlfa1.setText("alfa 1");

        lblAlfa3.setText("alfa 3");

        sldAlfa4.setMajorTickSpacing(30);
        sldAlfa4.setMaximum(175);
        sldAlfa4.setMinimum(5);
        sldAlfa4.setPaintLabels(true);
        sldAlfa4.setValue(90);
        sldAlfa4.setName("alfa4"); // NOI18N

        javax.swing.GroupLayout panelAngulosLayout = new javax.swing.GroupLayout(panelAngulos);
        panelAngulos.setLayout(panelAngulosLayout);
        panelAngulosLayout.setHorizontalGroup(
            panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAngulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAngulosLayout.createSequentialGroup()
                        .addComponent(lblAlfa1)
                        .addGap(18, 18, 18)
                        .addComponent(sldAlfa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngulosLayout.createSequentialGroup()
                        .addComponent(lblAlfa2)
                        .addGap(23, 23, 23)
                        .addComponent(sldAlfa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngulosLayout.createSequentialGroup()
                        .addComponent(lblAlfa3)
                        .addGap(23, 23, 23)
                        .addComponent(sldAlfa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngulosLayout.createSequentialGroup()
                        .addComponent(lblAlfa4)
                        .addGap(23, 23, 23)
                        .addComponent(sldAlfa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAngulosLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblControlBrazos)))
                .addGap(165, 165, 165))
        );
        panelAngulosLayout.setVerticalGroup(
            panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAngulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblControlBrazos)
                .addGap(27, 27, 27)
                .addGroup(panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlfa1)
                    .addComponent(sldAlfa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlfa2)
                    .addComponent(sldAlfa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlfa3)
                    .addComponent(sldAlfa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelAngulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlfa4)
                    .addComponent(sldAlfa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        topView.setBackground(new java.awt.Color(255, 255, 255));

        armView.setBackground(new java.awt.Color(255, 255, 255));

        canvas1.setPreferredSize(null);

        canvas2.setPreferredSize(null);

        lblArtCPosX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtDPosY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtAPosY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtCPosY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtDPosZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtB.setText("Articulacion b");

        lblArtAPosX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtAPosZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtA.setText("Articulacion a");

        jLabel4.setText("Articulacion d");

        lblArtBPosY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPosY.setText("Y");

        lblArtBPosZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtBPosX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblArtC.setText("Articulacion c");

        lblArtCPosZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPosX.setText("X");

        lblArtDPosX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPosZ.setText("Z");

        javax.swing.GroupLayout pnlCoordenadasLayout = new javax.swing.GroupLayout(pnlCoordenadas);
        pnlCoordenadas.setLayout(pnlCoordenadasLayout);
        pnlCoordenadasLayout.setHorizontalGroup(
            pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                        .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                                .addComponent(lblArtA)
                                .addGap(47, 47, 47)
                                .addComponent(lblArtAPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lblArtAPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblArtAPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtB)
                                    .addComponent(lblArtC))
                                .addGap(47, 47, 47)
                                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtBPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArtCPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtBPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArtCPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtBPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArtCPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47)
                                .addComponent(lblArtDPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lblArtDPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblArtDPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblPosX)
                        .addGap(93, 93, 93)
                        .addComponent(lblPosY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPosZ)
                        .addGap(57, 57, 57))))
        );
        pnlCoordenadasLayout.setVerticalGroup(
            pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPosX)
                    .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPosZ)
                        .addComponent(lblPosY)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtA)
                    .addComponent(lblArtAPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtAPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtAPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                        .addComponent(lblArtB)
                        .addGap(24, 24, 24)
                        .addComponent(lblArtC))
                    .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                        .addComponent(lblArtBPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblArtCPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                        .addComponent(lblArtBPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblArtCPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCoordenadasLayout.createSequentialGroup()
                        .addComponent(lblArtBPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblArtCPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlCoordenadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblArtDPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtDPosY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtDPosZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(topView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAngulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(topView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(221, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(panelAngulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(pnlCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas armView;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAlfa1;
    private javax.swing.JLabel lblAlfa2;
    private javax.swing.JLabel lblAlfa3;
    private javax.swing.JLabel lblAlfa4;
    private javax.swing.JLabel lblArtA;
    private javax.swing.JLabel lblArtAPosX;
    private javax.swing.JLabel lblArtAPosY;
    private javax.swing.JLabel lblArtAPosZ;
    private javax.swing.JLabel lblArtB;
    private javax.swing.JLabel lblArtBPosX;
    private javax.swing.JLabel lblArtBPosY;
    private javax.swing.JLabel lblArtBPosZ;
    private javax.swing.JLabel lblArtC;
    private javax.swing.JLabel lblArtCPosX;
    private javax.swing.JLabel lblArtCPosY;
    private javax.swing.JLabel lblArtCPosZ;
    private javax.swing.JLabel lblArtDPosX;
    private javax.swing.JLabel lblArtDPosY;
    private javax.swing.JLabel lblArtDPosZ;
    private javax.swing.JLabel lblControlBrazos;
    private javax.swing.JLabel lblDespX;
    private javax.swing.JLabel lblDespY;
    private javax.swing.JLabel lblPinza;
    private javax.swing.JLabel lblPosX;
    private javax.swing.JLabel lblPosY;
    private javax.swing.JLabel lblPosZ;
    private javax.swing.JLabel lblRotacion;
    private javax.swing.JPanel panelAngulos;
    private javax.swing.JPanel panelDesplazamiento;
    private javax.swing.JPanel pnlCoordenadas;
    private javax.swing.JSlider sldAlfa1;
    private javax.swing.JSlider sldAlfa2;
    private javax.swing.JSlider sldAlfa3;
    private javax.swing.JSlider sldAlfa4;
    private javax.swing.JSlider sldDespX;
    private javax.swing.JSlider sldDespY;
    private javax.swing.JButton sldPinza;
    private javax.swing.JSlider sldRotacion;
    private java.awt.Canvas topView;
    // End of variables declaration//GEN-END:variables
    public void reset(boolean state){
        //get
    }
    public Model getModel(){
        return model;
    }
    private void asignEvents(){
        Component componentsPanelAngulos[];
        //panelAngulos.getComponent();
        componentsPanelAngulos = new Component[panelAngulos.getComponentCount()];
        componentsPanelAngulos = panelAngulos.getComponents();
        for (Component component : componentsPanelAngulos) {
            /*
            componente.setEnabled(enable);
            if (componente instanceof Container) {
                activarComponentes((Container)componente, enable);
            }
*/          
            if(component instanceof JSlider){
                //JComboBox combo = (JComboBox) e.getSource();        
                //miApp.seleccionarTriangulo();
                
                System.out.println(component.toString());
                ((JSlider) component).addChangeListener(getController());
                
            }
        }
        System.out.println("# de componentes :" + panelAngulos.getComponentCount());
        
        Component componentPaneDesplazamiento[];
        //panelDesplazamiento.getComponent();
        componentPaneDesplazamiento = new Component[panelDesplazamiento.getComponentCount()];
        componentPaneDesplazamiento = panelDesplazamiento.getComponents();
        for (Component component : componentPaneDesplazamiento) {
            /*
            componente.setEnabled(enable);
            if (componente instanceof Container) {
                activarComponentes((Container)componente, enable);
            }
*/          
            if(component instanceof JSlider){
                //JComboBox combo = (JComboBox) e.getSource();        
                //miApp.seleccionarTriangulo();
                
                System.out.println(component.toString());
                ((JSlider) component).addChangeListener(getController());
                
            }
        }
        System.out.println("# de componentes :" + panelDesplazamiento.getComponentCount());
        
    }

    /**
     * @return the panelAngulos
     */
    public javax.swing.JPanel getPanelAngulos() {
        return panelAngulos;
    }

    /**
     * @param panelAngulos the panelAngulos to set
     */
    public void setPanelAngulos(javax.swing.JPanel panelAngulos) {
        this.panelAngulos = panelAngulos;
    }

    /**
     * @return the panelDesplazamiento
     */
    public javax.swing.JPanel getPanelDesplazamiento() {
        return panelDesplazamiento;
    }

    /**
     * @param panelDesplazamiento the panelDesplazamiento to set
     */
    public void setPanelDesplazamiento(javax.swing.JPanel panelDesplazamiento) {
        this.panelDesplazamiento = panelDesplazamiento;
    }

    /**
     * @return the armView
     */
    public java.awt.Canvas getLateralView() {
        return canvas2;
    }

    /**
     * @param armView the armView to set
     */
    public void setLateralView(java.awt.Canvas armView) {
        this.armView = armView;
    }

    /**
     * @return the topView
     */
    public java.awt.Canvas getTopView() {
        return canvas1;
    }

    /**
     * @param topView the topView to set
     */
    public void setTopView(java.awt.Canvas topView) {
        this.topView = topView;
    }
    
    // Getters for the sliders
    public JSlider getSldAlfa1() {
        return sldAlfa1;
    }

    public JSlider getSldAlfa2() {
        return sldAlfa2;
    }

    public JSlider getSldAlfa3() {
        return sldAlfa3;
    }

    public JSlider getSldAlfa4() {
        return sldAlfa4;
    }

    public JSlider getSldDespX() {
        return sldDespX;
    }

    public JSlider getSldDespY() {
        return sldDespY;
    }

    public JButton getSldPinza() {
        return sldPinza;
    }

    public JSlider getSldRotacion() {
        return sldRotacion;
    }
    
    // Setters for the lables

    public JLabel getLblArtAPosX() {
        return lblArtAPosX;
    }

    public JLabel getLblArtAPosY() {
        return lblArtAPosY;
    }

    public JLabel getLblArtAPosZ() {
        return lblArtAPosZ;
    }

    public JLabel getLblArtBPosX() {
        return lblArtBPosX;
    }

    public JLabel getLblArtBPosY() {
        return lblArtBPosY;
    }

    public JLabel getLblArtBPosZ() {
        return lblArtBPosZ;
    }

    public JLabel getLblArtCPosX() {
        return lblArtCPosX;
    }

    public JLabel getLblArtCPosY() {
        return lblArtCPosY;
    }

    public JLabel getLblArtCPosZ() {
        return lblArtCPosZ;
    }

    public JLabel getLblArtDPosX() {
        return lblArtDPosX;
    }

    public JLabel getLblArtDPosY() {
        return lblArtDPosY;
    }

    public JLabel getLblArtDPosZ() {
        return lblArtDPosZ;
    }
    
    
}
